[package]
name = "jrip-ipp"
version.workspace = true
edition.workspace = true
[dependencies]
rip-core.workspace = true
rip-ipp.workspace = true
rip-jobs.workspace = true
rip-storage.workspace = true
axum = "0.8"
mdns-sd = "=0.21.0"
url = "2"
tokio.workspace = true
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
[dev-dependencies]
tempfile = "3"
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
